export const CASE_STATUSES = [
  'Demand Posted',
  'Demand Expired',
  'Eviction Service',
  'Answer Filed',
  'Court Date',
  'Consent',
  'Writ - Date Requested',
  'Writ - Date Available',
  'Writ - Date Received',
  'Eviction - To Be Scheduled',
  'Eviction - Date Scheduled',
  'Eviction - Completed',
  'Dismissed',
  'Appeal',
  'Bankruptcy',
  'Dismissed – Filed in Error',
  'Dismissed – Paid',
  'Skipped/Vacated',
];
